[package]
name = "vec-entry"
version = "0.1.0"
edition = "2021"
description = "An `entry` API extension for `Vec` and `VecDeque`"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
